name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build stage
      run: go build -v ./... -o $GITHUB_WORKSPACE/test-app
    
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses:  actions/upload-artifact@v2
      with:
        name: test-app
        path: $GITHUB_WORKSPACE/test-app 