name: Go

env:
  artifact_name: test-app

on:
  pull_request:
    branches: [ main ]
  workflow_call:
    outputs:
      artifact_name:
        description: "The name of the artifact"
        value: ${{ env.artifact_name }}


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - run: mkdir -p $RUNNER_TEMP/artifacts/

    - name: Build
      run: go build -o $RUNNER_TEMP/artifacts/${{ env.artifact_name }}

    - run: ls -R $RUNNER_TEMP/artifacts/

    - name: Upload artifact
      uses:  actions/upload-artifact@v2
      with:
        name: ${{ env.artifact_name }}
        path: /home/runner/work/_temp/artifacts/*
