name: Go

on:
  push:
    branches: [ 'releases/**' ]  

jobs:
  create-build-artifact:
    uses: ./.github/workflows/go.yml

  release:
    runs-on: ubuntu-latest
    needs: create-build-artifact
    steps:
    - uses: actions/checkout@v2
    - run: mkdir -p $RUNNER_TEMP/artifacts/
    - name: Get artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ needs.create-build-artifact.outputs.artifact_name }} 
        path: ${{ runner.temp }}/artifacts

    - name: Create a release
      run: gh release create $GITHUB_RUN_ID ${{ needs.create-build-artifact.outputs.artifact_name }} -t $GITHUB_REF_NAME ${{ runner.temp }}/artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
