name: Go

on:
  push:
    branches: [ main ]  

env:
  artifact_name: test-app

jobs:
  create-build-artifact:
    uses: ./.github/workflows/go.yml
    with:
      artifact_name: ${{ env.artifact_name }}

  release:
    runs-on: ubuntu-latest
    needs: create-build-artifact
    steps:
    - uses: actions/checkout@v2
    
    - name: Display structure of downloaded files
      run: ls -R
      
    - name: Get artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ env.artifact_name }}

    - name: Create a release
      run: hub release create -a  -m InitialRelease $GITHUB_RUN_ID 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}