name: Go

on:
  push:
    branches: [ main ]  

jobs:
  create-build-artifact:
    uses: ./.github/workflows/go.yml

  release:
    runs-on: ubuntu-latest
    needs: create-build-artifact
    steps:
    - uses: actions/checkout@v2
    
    - name: Display structure of downloaded files
      run: ls -R
      
    - name: Get artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ needs.create-build-artifact.outputs.artifact_name }} 

    - name: Create a release
      run: hub release create -a ${{ needs.create-build-artifact.outputs.artifact_name }} -m InitialRelease $GITHUB_RUN_ID 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}